KadhoWebsite/KadhoWebsite/Controllers/TOSController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KadhoWebsite.Controllers
{
    public class TOSController : Controller
    {
        //
        // GET: /TOS/
        public ActionResult Index()
        {
            return View();
        }
	}
}

KadhoWebsite/KadhoWebsite/Views/Template/About.cshtml
<div class="text-content">
    <h2 name="who">Who we are</h2>
    <p>
        We are leading innovators in translating the science of brain development and enhancement into interactive tools that are readily accessible to end users (smart phone/tablet apps, web, wearable technology, games, etc.).
        We are passionate about changing the world one child at a time.
        We are a world-class team made up of passionate and highly motivated scientists, engineers, game developers, artists, designers, and learning specialists.
        Our team is actively engaged with leading academics around the world to integrate scientifically advanced auditory and visual stimuli into every day’s lives in order to enhance the neurological capabilities of humans.
    </p>


    <h2 name="foundation"> We Are Preserving the Innate Abilities That Children Are Born With</h2>
    <p>
        We aim to help build the foundation of a child’s brain so that he or she is better wired for cognitive development. Kadho aims to provide an enriched environment for brain development beyond what any non-technological environment possibly could. We have developed a highly scientific approach that will help build a solid neurofoundation™ for all children. With Kadho, children have an advantage in enhancing their attention span, memory, and of course, language-learning abilities.

        Kadho is firmly rooted in science. Our products are based on over 50 years of research and are verified by our own studies. Our toys and games are designed under the guidance of renowned experts. Our team is actively engaged with leading academics, scientist, pediatricians, and early educators around the world to integrate scientifically advanced auditory and visual stimuli into everyday lives in order to enrich the neurological development of children. Each of our products are carefully developed under a team of researchers. We know that Kadho works.
    </p>
</div>

KadhoWebsite/KadhoWebsite/Views/Template/FAQ.cshtml
<div class="text-content">
    <h1 style="margin-bottom: 20px; text-align: left; font-size: 2em; font-weight: normal;">Frequently Asked Questions</h1>

    <h2 class="faq-question">What do you do?</h2>
    <p class="faq-answer">
        We create products (games and ebooks) to enrich a child’s cognitive development.
        Our products aim to enhance language development, musicality, and memory skills,
        to maintain visual abilities, and to improve a child’s ability to learn multiple languages later in life.
        Kadho’s initial products consist of a pipeline of mobile applications that are backed by over 50 years of scientific research.
        The applications will consist of games that expose children to a series of neurological
        stimuli (sounds, visual tasks, etc.),that aim to help a child grow to their full potential.
    </p>

    <h2 class="faq-question">Who’s Mochu?</h2>
    <p class="faq-answer">
        Mochu, the penguin, is one of our main characters that a child interacts with through games,
        songs, and books. Mochu was carefully designed and created to provide the child with positive social and emotional support,
        as well as engagement and motivation.
    </p>

    <h2 class="faq-question">Have you tested your platforms?</h2>
    <p class="faq-answer">
        We have validated our games for both safety and efficacy in clinical-type settings.
        In addition, we have world-renowned advisors in child development, early education,
        and neuroscience who provide guidance on our product development. We have demonstrated significant positive
        results in several in-house studies with children from as young as 8 months to as old as 7 years of age.
        We have shown significant efficacy with as little as 7 hours of total game play over 4 weeks,
        and the improved effect has been shown to be maintained and enhanced through continued play.
    </p>

    <h2 class="faq-question">How can I know this is working?</h2>
    <p class="faq-answer">
        Monitoring the effect of our products is an essential component of the package that
        Kadho has to offer. When we first started this journey, parents asked us how they could quantify the effect of these games.
        While designing the Kadho Curriculum, we added an “analytic dashboard”
        that monitors kids’ performance throughout the game. We include tangible endpoints that parents can connect with.
        These endpoints and data are obtained through “audio and visual tasks” embedded within the game.
    </p>

    <h2 class="faq-question">How much does your services cost?</h2>
    <p class="faq-answer">
        Basic membership to Kadho.com is free, and non-subscribing members have access to a limited number of the games and features on Kadho.
        Paid subscribers have full access to the Kadho program, which includes all the games.
    </p>

    <h2 class="faq-question">What products do you have?</h2>
    <p class="faq-answer">
        We have interactive digital books, games, and songs that help enrich the cognitive development
        of skills needed for language learning, musical abilities, working memory, impulse control, reasoning, and intelligence.
    </p>

    <h2 class="faq-question">How often does my child need to play with your game to see benefits?</h2>
    <p class="faq-answer">
        We recommend less than 20 minutes of play a day for children under 2 and less than 40 for children under 4.
        With as little as 15 minutes of play a day, we would expect to see results in as little as 3 weeks.
    </p>

    <h2 class="faq-question">
        I was told that screen time and media for children under two is not recommended.
        <br />Is that true?
    </h2>
    <p class="faq-answer">
        It would be unfair to categorize all screen time under the same category. Several decades ago,
        televisions were the only screen time available. Now we have electronic games, laptops, smartphones,
        tablets, and augmented reality.
        Technology today allows for amazing opportunities for children that you previously couldn’t provide through traditional means.
        However, we do understand parents’ concerns about technology use with children,
        and we feel that for the very young, it is inevitable now and in the future. Media and technology will be part of our lives,
        and we need to be able to incorporate them in a sensible way and make smart decisions on what media we allow our children to use.
        Data suggest that children from eight months to eight years are exposed to over 4 hours of TV a day;
        we believe that this is too much screen time spent on non-enriching media,
        and it’s essential that, during the critical periods of brain development,
        children are not wasting developmental opportunities on “wrong” screen time.
        The American Academy of Pediatrics discourages parents from using media with
        children under 24 months of age because there is a lack of evidence on children learning
        from television or videos before age 2. However, their guidelines do not cover
        interactive content that can be created with today’s technology.
        Research shows that content can make a difference.
        To address these concerns, we have experts in pediatrics, child development,
        and early education and very technologically conservative advisors on our board to provide guidance on the development of our products.
    </p>

    <h2 class="faq-question">Can iPads substitute for actual parent-child interactions like talking, reading, and singing?</h2>
    <p class="faq-answer">
        Although technology is changing how children learn and opening up new and exciting methods of teaching,
        we believe nothing is better than real parent-child interactions.
        Technology should never be used as a full-time babysitter to replace parent and child interactions.
        Instead it should be there to augment enrichment.
        Children need to play outdoors and get multisensory stimulation to help properly develop their brain.
        If the only thing children did was play outdoors, it would not be recommended as well,
        so the same logic needs to be applied to technology, and balance is key to proper brain development.
        We would say not to use our software if you as a parent have the resources to hire multiple babysitters
        who are fluent in different languages, as well as scientists, child development experts,
        and early educators to provide enriching games and exercises.
        However, most parents do not have the resources to provide such an environment,
        so we recommend playing, talking, singing, reading, and socializing with your children,
        then adding Kadho products to help enrich your child’s life even more.
    </p>


</div>

KadhoWebsite/KadhoWebsite/Views/Template/Main.cshtml
<div class="content">
    <img src="@Url.Content("~/Content/images/logo.png")">

    <h1 class="title">
        Transforming Life through Sound and Science
    </h1>

    <div ng-show="signInAttempted">

        <modal-dialog show='isPlaying' width='500px'>
            <vimeo height="270"
                   width="480"
                   control-boolean="isPlaying" vid="106073436" pid="1"></vimeo>
        </modal-dialog>
        <div style="padding: 20px;">
            <h2 class="home-subtitle"><a ng-click="play()">Watch our video</a></h2>
        </div>
        <div ng-show="user">
            <h1 class="waitinline">
                {{user.name}}, you're #{{user.positionInLine}} in line!
            </h1>
            <div>
                Not <a ng-click="clearUser()">{{user.email}}?</a>
            </div>
        </div>


        <modal-dialog show='displayCompleteSignupModal' dialog-title='Almost there!' width='375px'>

            <form name="confirmForm"
                  ng-controller="ConfirmFormController"
                  ng-submit="submit()"
                  class="sign-up"
                  novalidate>
                <div class="field">
                    <label>Name</label>
                    <div class="error" ng-show="(buttonAttempt || confirmForm.given_name.$dirty) && confirmForm.given_name.$invalid">
                        required
                    </div>
                    <input name="given_name"
                           placeholder="Name"
                           type="text"
                           ng-model="new_user.name"
                           autofocus
                           required>
                </div>
                <div class="field">
                    <label>Email</label>
                    <div class="error" ng-show="(buttonAttempt || confirmForm.email.$dirty) && confirmForm.email.$invalid">
                        valid email required
                    </div>
                    <input placeholder="Email"
                           type="email"
                           ng-model="new_user.email"
                           name="email" required />
                </div>


                <div class="field">
                    <label>Zip code</label>
                    <div class="error" ng-show="(buttonAttempt || confirmForm.zip.$dirty) && confirmForm.zip.$invalid">
                        Enter valid zip
                    </div>
                    <input ui-mask="99999"
                           name="zip"
                           ng-model="new_user.zip">
                </div>

                <div class="field">
                    <label>Children Ages</label>
                    <label class="hidden">Children Ages</label>
                    <input placeholder="Children ages separated by spaces or commas" type="text" ng-model="new_user.childrenAge" name="childrenAge" />
                </div>

                <p class="sign-up-disclaimer">
                    By signing up, you agree to our <a href="@Url.Action("Index", "TOS")" target="_blank">
                        Terms of
                        service.
                    </a>
                </p>

                <button type="submit" class="sign-up-submit-btn btn btn-primary btn-lrg btn-full" ng-disabled="disableSubmit">
                    <span ng-show="(confirmForm.$valid || confirmForm.$pristine) && !disableSubmit">Complete sign up</span>
                    <span ng-show="!confirmForm.$valid && confirmForm.$dirty && !disableSubmit">Fix errors above</span>
                    <span ng-show="disableSubmit">Please wait...</span>
                </button>

                <div ng-switch="signupMessage" class="sign-up-error" ng-animate=" 'animate' ">
                    <div ng-switch-when="InvalidZip">
                        Please enter a valid US zip code.
                    </div>
                    <div ng-switch-when="InvalidName">
                        Please enter a valid name! We'd like to know who is interested :).
                    </div>
                    <div ng-switch-when="InvalidEmail">
                        Please enter a valid email! Your email will only be used to contact you about Kadho!
                    </div>
                    <div ng-switch-when="FailEmailExist">
                        You're already on the waitlist!
                        <br />Please check your email for a link to view your spot in line!
                        <br />Can't find the email? <a href="#" ng-click="resendEmail()">Click here</a> to re-send the link.
                    </div>
                    <div ng-switch-when="Error">
                        Oops! Looks like an error has occurred while signing you up!
                        Please try again in a moment and if this happens again, please email us at kadho@kadho.com!
                    </div>

                    <div ng-switch-when="ResendEmailError">
                        Oops! Looks like an error has occurred while resending you the email!
                        Please try again in a moment and if this happens again, please email us at kadho@kadho.com!
                    </div>
                    <div ng-switch-when="ResendEmailSuccess">
                        Email has been resent! Please check your email!
                    </div>
                    <div ng-switch-when="RecentlySentEmail">
                        An email has recently been sent already! Please check your email!
                    </div>
                </div>
            </form>

        </modal-dialog>


        <div ng-show="!user">
            <div class="sign-up-main">
                <form name="emailform"
                      ng-controller="SignupFormController"
                      ng-submit="submit()"
                      class="sign-up"
                      novalidate>
                    <input placeholder="Email" type="email" ng-model-options="{ updateOn: 'default blur', debounce: {'default': 500, 'blur': 0} }" ng-model="new_user.email" name="email" required="" class="ng-pristine ng-invalid ng-invalid-required ng-valid-email">
                    <button type="submit" class="sign-up-submit-btn btn btn-primary btn-lrg btn-full customButton">
                        <span ng-show="emailform.$valid || emailform.$pristine" class="">
                            Complete sign up
                        </span>
                        <span ng-show="!emailform.$valid &amp;&amp; emailform.$dirty" class="ng-hide">
                            Enter a valid email above
                        </span>
                    </button>

                    <div style="margin: auto; margin-top: 10px; margin-bottom: 10px; width: 240px;">
                        <div style="margin: auto;">
                            <div style="float: left;">
                                <div style="margin-top: 5px;" google-signin=""
                                     client-id='151458216512-34e39r5giqgu6hdri2dhklms1no4fn69'
                                     after-signin="oauthSignIn(oauth)"></div>
                            </div>
                            <div style="float: left; margin-left: 10px;">
                                <div style="margin: auto; margin-top: 0px;" class="fblogin" ng-click="fbLogin()">
                                    <i class="fbloginIcon"></i>
                                    Sign-in
                                </div>
                            </div>
                        </div>
                    </div>
                    <br class="clear" />
                    <div class="home-stat">
                        Takes just <strong>15 seconds</strong> to sign up!
                    </div>
                </form>
            </div>

        </div>
    </div>

</div>

KadhoWebsite/KadhoWebsite/Views/Template/Science.cshtml
<div class="text-content">

<h2 name="science">The Scientific Drive Behind Kadho’s Core Technology</h2>
<p>
Kadho is applying the fundamentals of neuroscience, early childhood education, and immersion/motivation principles to create fun, engaging, and interactive games and ebooks. We are indeed developing the next generation of educational games with quantitative parental tools to monitor children’s performance over time.
</p>

<h2 name="why">Why Early Experiences Matter?</h2>
<p>
    Science has shown that the first few years of a child’s life are the most critical for success later on. It is during these years that children’s brains develop at their fastest and form the neural connections for the rest of their life. This critical time is a “window of opportunity” when the neural circuitry of children’s brains is developing and building proper structures that underlie growing neurobehavioral capacity and the development of neuronal systems providing sensory, perceptual, and basic memory functions that form the neuro-foundation for future cognitive abilities.

    During these “windows of opportunity,” when the window is open, a child learns more easily than he or she ever will again. With the right opportunities and the right environment, a child will develop the neuro-foundations for language, communication, memory, physical coordination, and self-awareness. In order to take advantage of these critical periods, the brain needs to be stimulated appropriately so that it lays down the neuronal circuitry needed for various abilities. The critical period of a child’s development offers great opportunities for each child, but it is also the period when those opportunities can be wasted. One shining example is the ability to learn languages. One of the most fundamental and at the same time most surprising abilities of newborns is that they are able to distinguish all the sounds of the world’s languages. In other words, they are born as “citizens of the world,” ready to learn any natural language. However, this gift slowly dwindles in the first year of life.

    Our mission is to ensure that all children have a good neural foundation for the rest of their lives. At birth, the child’s brain is only about 25 percent connected, but within their first year, the connections reach 75 percent complete, and within the third year, ninety percent of the brain’s wiring has been formed. This literally shows that early experiences will plant the seeds that will allow a child to reach his or her maximum potential.

</p>

</div>